#!/usr/bin/env ruby
# frozen_string_literal: true

require 'aoc_2020'

# target_class = Object.const_get('Aoc2020::' + ARGV.shift.to_s.capitalize).new
# puts "target_class = #{target_class}"
# Object.const_get(target_class + ".#{ARGV.shift}")
